/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32f411xe.h"
#include <stdint.h>


int main(void)
{
    /* Enable FPU */
    SCB->CPACR |= ((3UL << 20) | (3UL << 22));

    /* Enable GPIOA clock */
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;

    /* Set PA5 as output (MODER5 = 01) */
    GPIOA->MODER &= ~(3U << (5 * 2));  // clear bits
    GPIOA->MODER |=  (1U << (5 * 2));  // set as output

    while(1)
    {
    	GPIOA->ODR ^= (1U << 5);   // toggle PA5

    	for (volatile uint32_t i = 0; i < 500000; i++); // crude delay
    }

}
