/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32f411xe.h"
#include <stdint.h>

int main(void)
{
    /* Enable FPU */
    SCB->CPACR |= ((3UL << 20) | (3UL << 22));

    /* Enable GPIOA and GPIOC clock */
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;
    (void)RCC->AHB1ENR;

    /* PA5 as output */
    GPIOA->MODER &= ~(3U << (5 * 2));
    GPIOA->MODER |=  (1U << (5 * 2));

    /* PC13 as input */
    GPIOC->MODER &= ~(3U << (13 * 2));

    while(1)
    {
        /* Button is active LOW */
        if(!(GPIOC->IDR & (1U << 13)))
        {
            GPIOA->BSRR = (1U << 5);   // LED ON
        }
        else
        {
            GPIOA->BSRR = (1U << (5 + 16)); // LED OFF
        }
    }
}
